### PR TITLE
add github1s.com

### PR DESCRIPTION
**Pull request by mrmartineau**
added support for github1s.com. I wasn't sure about the cli modifier (`1s`), so let me know if you want something different/better.

More info: https://github.com/conwnet/github1s

### CODE REVIEW

**Comment by kachkaev** [comment]
Very cool project, thanks for the find @mrmartineau! Let’s wait for the tool to settle a bit, it is currently too new.

Also, WRT the keyword, I'll be leaning towards `1` instead of `1s` just to keep all keywords one character long. I know that this does not scale, but I hope we won’t need to change the rule too soon.

Meanwhile, you can replace `njt.now.sh` with `njt-git-fork-mrmartineau-main.kachkaev.now.sh` in your search tool and enjoy jumping to `github1s` without having to wait for this PR!

Please ping me in a few weeks (say, mid/end March) – we’ll see where github1s is and if it’s not yet abandoned, renamed or reformed too much, I'm happy to add a new keyword 🙌

**Comment by mrmartineau** [comment]
no problem, I understand. Probably good to wait a bit because there's also a fork of github1s called github.surf which looks like it is adding some more features, but I don't know how it might affect github1s..

**Comment by iamandrewluca** [comment]
GitHub now officially supports this https://github.dev/kachkaev/njt

**Comment by kachkaev** [comment]
Yeah that's a very good point @iamandrewluca!

@mrmartineau would you be interested in updating your PR? No worries if you no longer have time for this – I’ll happy to implement `d` too 🙂

**Comment by iamandrewluca** [comment]
@kachkaev I already started implementing it. But there is a problem. `d` is aliased for `h` (homepage)

**Comment by kachkaev** [comment]
Thanks for creating #143 @iamandrewluca! @mrmartineau WDYT of closing this PR in favour of that one?

**Comment by kachkaev** [comment]
@mrmartineau you can now use `njt package-name .` and land on `github.dev`, which is a successor of `github1s.com`. Many thanks for your contribution and for sharing github1s, which is a pretty inspiring project! 🙌

**Pull request closed without merging**
