### PR TITLE
feat: add support for searching anything on npm

### LINKED ISSUE #39: Support searching npm directly
Sometimes I want to search on npm.

- I can go to npmjs and search
- I can add npmjs as search engine and search directly in address bar

Would be great to have also this into njt, having `f` (find) as a keyword (`s` is already used)

```
njt -> google map react f -> https://www.npmjs.com/search?q=google+map+react
```

### PR DESCRIPTION
**Pull request by iamandrewluca**
Closes #39

### CODE REVIEW

**Comment by iamandrewluca** [comment]
It seems that the search string is stripped here https://github.com/kachkaev/njt/blob/f48b08307ae5feb6c5b3f3461a1d7987e5e4f638/src/pages/api/jump.ts#L11

**Comment by kachkaev** [comment]
Hi @iamandrewluca! Let’s discuss the feature in https://github.com/kachkaev/njt/issues/39 🙌

**Review by kachkaev — CHANGES_REQUESTED** [review]
See https://github.com/kachkaev/njt/issues/39#issuecomment-729671711

**Comment by iamandrewluca** [comment]
See https://github.com/kachkaev/njt/issues/39#issuecomment-729674745

**Pull request closed without merging**
